---
apiVersion: v1
kind: Service
metadata:  
  name: dmbc-discovery
  labels:
    app: dmbc-discovery
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dmbc-discovery
  type: ClusterIP