apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2YXVsdDpzZWNyZXQvZGF0YS9kbS1rOHMtZGV2MDIvZG1hcmtldC9kb2NrZXJodWIjRE9DS0VSX1JFUE9fVVNFUiIsInBhc3N3b3JkIjoidmF1bHQ6c2VjcmV0L2RhdGEvZG0tazhzLWRldjAyL2RtYXJrZXQvZG9ja2VyaHViI0RPQ0tFUl9SRVBPX1BBU1NXT1JEIiwiYXV0aCI6ImRtRjFiSFE2YzJWamNtVjBMMlJoZEdFdlpHMHRhemh6TFdSbGRqQXlMMlJ0WVhKclpYUXZaRzlqYTJWeWFIVmlJMFJQUTB0RlVsOVNSVkJQWDFWVFJWSTZkbUYxYkhRNmMyVmpjbVYwTDJSaGRHRXZaRzB0YXpoekxXUmxkakF5TDJSdFlYSnJaWFF2Wkc5amEyVnlhSFZpSTBSUFEwdEZVbDlTUlZCUFgxQkJVMU5YVDFKRSJ9fX0=
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://10.157.0.109:8200"
    vault.security.banzaicloud.io/vault-auth-method: "kubernetes"
    vault.security.banzaicloud.io/vault-path: "dm-k8s-dev02"
    vault.security.banzaicloud.io/vault-role: "vault-auth"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  name: dockerhub
type: kubernetes.io/dockerconfigjson