---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmbc02
  labels:
    app: dmbc02
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd