---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmbc03
spec:
  template:
    spec:
      serviceAccountName: dmbc-configmap-updater
      initContainers:
      - command:
          - sh
          - -c
          - |
            #!/usr/bin/env bash -e
            echo "Updating of dmbc04-config configmap"
            echo "POD_IP: $POD_IP"
            kubectl get cm dmbc03-config -o yaml | sed -e "s|0.0.0.0|$POD_IP|g" | kubectl apply -f -

            echo "End"
        image: bitnami/kubectl:1.21.2
        imagePullPolicy: IfNotPresent
        name: configmap-updater
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP