---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmbc01
  labels:
    app: dmbc01
    dmbc: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dmbc01
  strategy:
    type: Recreate
  template:
    metadata:
      name: dmbc01
      labels:
        app: dmbc01
        dmbc: "true"
    spec:
      containers:
      - name: dmarket-blockchain
        image: globalgames/dmarket-blockchain:latest
        imagePullPolicy: Always
        env:
          - name: RUST_LOG
            value: info
          - name: RUST_BACKTRACE
            value: "1"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /src/app/var/keys
          name: dmbc01-keys
        - mountPath: /src/app/var/db
          name: dmbc01
        - mountPath: /src/app/etc
          name: dmbc01-config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dmbc01
        persistentVolumeClaim:
          claimName: dmbc01
      - name: dmbc01-keys
        secret:
          defaultMode: 420
          secretName: dmbc01-keys
      - configMap:
          defaultMode: 420
          name: dmbc01-config
        name: dmbc01-config
          
