---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmbc01
  labels:
    app: dmbc01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd