---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmbc03
  labels:
    app: dmbc03
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd