---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmbc04
  labels:
    app: dmbc04
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd