kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dmbc-configmap-updater
  labels:
    app: dmbc
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "update", "patch"]