kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dmbc-configmap-updater
  labels:
    app: dmbc
subjects:
- kind: ServiceAccount
  name: dmbc-configmap-updater
roleRef:
  kind: Role
  name: dmbc-configmap-updater
  apiGroup: rbac.authorization.k8s.io