apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2YXVsdDpzZWNyZXQvZGF0YS9jb21tb24vZG9ja2VyaHViI0RPQ0tFUl9SRVBPX1VTRVIiLCJwYXNzd29yZCI6InZhdWx0OnNlY3JldC9kYXRhL2NvbW1vbi9kb2NrZXJodWIjRE9DS0VSX1JFUE9fUEFTU1dPUkQiLCJhdXRoIjoiZG1GMWJIUTZjMlZqY21WMEwyUmhkR0V2WTI5dGJXOXVMMlJ2WTJ0bGNtaDFZaU5FVDBOTFJWSmZVa1ZRVDE5VlUwVlNPblpoZFd4ME9uTmxZM0psZEM5a1lYUmhMMk52YlcxdmJpOWtiMk5yWlhKb2RXSWpSRTlEUzBWU1gxSkZVRTlmVUVGVFUxZFBVa1E9In19fQ==
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://10.157.0.109:8200"
    vault.security.banzaicloud.io/vault-auth-method: "kubernetes"
    vault.security.banzaicloud.io/vault-path: "dm-k8s-dev01"
    vault.security.banzaicloud.io/vault-role: "vault-auth"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  name: dockerhub
type: kubernetes.io/dockerconfigjson
